CUDA_VISIBLE_DEVICES=1,0 \
torchrun \
--nproc_per_node 2 \
--nnodes 1 \
--node_rank 0 \
--master_addr localhost \
--master_port 6611 \
finetune.py \
--model_name_or_path "/home/minpengfei/Llama-3/Meta-Llama-3-8B-Instruct/" \
--data_path "/home/minpengfei/Llama-3/LLaMA-Factory/ruozhiba.json" \
--bf16 True \
--output_dir "/home/minpengfei/Llama-3/myllama" \
--num_train_epochs 100 \
--per_device_train_batch_size 1 \
--per_device_eval_batch_size 1 \
--gradient_accumulation_steps 16 \
--evaluation_strategy "no" \
--save_strategy "steps" \
--save_steps 5 \
--save_total_limit 1 \
--learning_rate 1e-5 \
--weight_decay 0.1 \
--adam_beta2 0.95 \
--warmup_ratio 0.01 \
--lr_scheduler_type "cosine" \
--logging_steps 1 \
--report_to "none" \
--model_max_length 2048 \
--gradient_checkpointing True \
--lazy_preprocess True \
--deepspeed "/home/minpengfei/Llama-3/LLaMA-Factory/config/ds_config_zero2.json" \
--use_lora \
--load_in_4bit \
--q_lora